# Generated by Django 4.1.5 on 2023-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sourceCode",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
